"""
pipeline/github/pr_creator.py
 
Creates GitHub PRs for validated Sigma rules.
 
Per PR:
  - New branch: rule/T{id}-{slug}
  - Commits rule YAML to rules/{filename}
  - PR body: validation summary + evidence events
  - Returns PRResult(pr_url, pr_number)
 
"""

import os
import json
import re
import textwrap
from dataclasses import dataclass
from pathlib import Path

from github import Github, GithubException
from dotenv import load_dotenv

load_dotenv()

DEBUG = os.getenv("PIPELINE_DEBUG", "").lower() in ("1", "true")

RULES_DIR = "rules"
MAX_EVIDENCE_EVENTS = 5       # events shown in PR body
MAX_CONDITION_LENGTH = 500    # cap on SQL condition in PR body


# ---------------------------------------------------------------------------
# Result type
# ---------------------------------------------------------------------------

@dataclass
class PRResult:
    pr_url: str
    pr_number: int
    branch_name: str
    rule_filename: str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _slugify(text: str, max_len: int = 40) -> str:
    """
    Convert rule title or technique name to a URL/filename-safe slug.
    Truncated to max_len to avoid Windows 255-char filename limit.
    """
    slug = text.lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")
    return slug[:max_len].rstrip("-")


def _rule_filename(technique_id: str, rule_yaml: str) -> str:
    """
    Derive rule filename from technique ID + rule title.
    Convention: T{id}-{slug}.yml
    Falls back to technique ID slug if title can't be parsed.
    """
    title = ""
    for line in rule_yaml.splitlines():
        line = line.strip()
        if line.startswith("title:"):
            title = line[len("title:"):].strip().strip("\"'")
            break

    slug = _slugify(title) if title else _slugify(technique_id)
    return f"{technique_id}-{slug}.yml"


def _branch_name(technique_id: str, rule_yaml: str) -> str:
    """Branch naming: rule/T{id}-{slug}"""
    filename = _rule_filename(technique_id, rule_yaml)
    stem = Path(filename).stem  # strip .yml
    return f"rule/{stem}"


def _format_evidence(missed_events: list[dict]) -> str:
    """Format missed events as a compact markdown block."""
    if not missed_events:
        return "_No missed events available._"

    lines = []
    for i, event in enumerate(missed_events[:MAX_EVIDENCE_EVENTS], 1):
        populated = {
            k: v for k, v in event.items()
            if v is not None and v != "" and k not in ("Channel",)
        }
        lines.append(f"**Event {i}:**")
        lines.append("```json")
        lines.append(json.dumps(populated, indent=2))
        lines.append("```")

    if len(missed_events) > MAX_EVIDENCE_EVENTS:
        lines.append(
            f"_...and {len(missed_events) - MAX_EVIDENCE_EVENTS} more events not shown._"
        )

    return "\n".join(lines)


def _format_fired_rules(fired_rules: list) -> str:
    """Format rules that fired last run — context for reviewer."""
    if not fired_rules:
        return "_No rules fired (first iteration or no prior run)._"

    lines = []
    for rb in fired_rules:
        condition = (rb.sql_query or "unavailable")[:MAX_CONDITION_LENGTH]
        lines.append(f"- **{rb.rule_title}**")
        lines.append(f"  ```sql\n  {condition}\n  ```")

    return "\n".join(lines)


def _build_pr_body(
    technique_id: str,
    technique_name: str,
    missed_events: list[dict],
    validation_feedback: str,
    fired_rules: list,
    fp_rate: float | None,
) -> str:
    """
    Build the PR body markdown.
    Structured for a reviewer to understand: what was missed, what was generated, how it validated.
    """
    fp_str = f"{fp_rate:.1%}" if fp_rate is not None else "N/A"

    body = textwrap.dedent(f"""\
        ## Detection Gap Closure — {technique_id}
 
        **Technique:** {technique_id} — {technique_name}
        **Generated by:** Defender Agent (automated)
        **Status:** All validation gates passed ✅
 
        ---
 
        ### Validation Summary
 
        | Gate | Result |
        |------|--------|
        | Schema Linter | ✅ Passed |
        | Attack Gate | ✅ Fired on attack sample |
        | Noise Gate | ✅ FP rate: {fp_str} |
 
        ---
 
        ### Evidence — Missed Events
 
        These events were not caught by existing rules and triggered this rule generation:
 
        {_format_evidence(missed_events)}
 
        ---
 
        ### Prior Rules That Fired (Existing Coverage)
 
        Rules that already fired on this technique — provided for context:
 
        {_format_fired_rules(fired_rules)}
 
        ---
 
        ### Reviewer Notes
 
        - Rule was generated by the defender agent and validated automatically
        - Verify detection logic is specific enough for your environment
        - Check FP rate against your own benign corpus before merging
        - This PR was opened automatically — human review required before merge
    """)

    return body


# ---------------------------------------------------------------------------
# Main creator
# ---------------------------------------------------------------------------

class PRCreator:

    def __init__(self):
        token = os.getenv("GITHUB_TOKEN")
        repo_name = os.getenv("GITHUB_REPO")

        if not token:
            raise EnvironmentError(
                "GITHUB_TOKEN not set — add to .env (needs repo scope)"
            )
        if not repo_name:
            raise EnvironmentError(
                "GITHUB_REPO not set — add to .env (format: owner/repo-name)"
            )

        self._gh = Github(token)
        self._repo = self._gh.get_repo(repo_name)

        if DEBUG:
            print(f"[pr_creator] Connected to repo: {repo_name}")

    def create_pr(
        self,
        technique_id: str,
        technique_name: str,
        rule_yaml: str,
        missed_events: list[dict],
        validation_result,           # ValidationResult from validation_pipeline
        fired_rules: list | None = None,
    ) -> PRResult:
        """
        Create a GitHub PR for a validated Sigma rule.

        Args:
            technique_id:       ATT&CK technique ID
            technique_name:     Human-readable name
            rule_yaml:          Validated Sigma YAML string
            missed_events:      Events that weren't caught — attached as evidence
            validation_result:  ValidationResult — used for FP rate in PR body
            fired_rules:        RuleBreakdown list from prior DetectionResult (optional)

        Returns:
            PRResult with pr_url, pr_number, branch_name, rule_filename
        """
        filename = _rule_filename(technique_id, rule_yaml)
        branch = _branch_name(technique_id, rule_yaml)
        rule_path = f"{RULES_DIR}/{filename}"

        if DEBUG:
            print(f"[pr_creator] {technique_id}: creating branch '{branch}'")

        # Get default branch HEAD commit SHA
        default_branch = self._repo.default_branch
        head_sha = self._repo.get_branch(default_branch).commit.sha

        # ── Early exit: check existing PR + content before touching branch ──
        open_prs = self._repo.get_pulls(
            state="open",
            head=f"{self._repo.owner.login}:{branch}",
        )
        existing_pr = next(iter(open_prs), None)

        fp_rate = getattr(validation_result, "fp_rate", None)
        feedback = getattr(validation_result, "feedback", "") or ""
        pr_body = _build_pr_body(
            technique_id=technique_id,
            technique_name=technique_name,
            missed_events=missed_events,
            validation_feedback=feedback,
            fired_rules=fired_rules or [],
            fp_rate=fp_rate,
        )

        if existing_pr:
            try:
                existing_file = self._repo.get_contents(rule_path, ref=branch)
                existing_content = existing_file.decoded_content.decode()
                content_unchanged = existing_content.strip() == rule_yaml.strip()
                body_unchanged = (
                    existing_pr.body or "").strip() == pr_body.strip()

                if content_unchanged and body_unchanged:
                    if DEBUG:
                        print(
                            f"[pr_creator] No changes detected for "
                            f"#{existing_pr.number} — skipping entirely"
                        )
                    return PRResult(
                        pr_url=existing_pr.html_url,
                        pr_number=existing_pr.number,
                        branch_name=branch,
                        rule_filename=filename,
                    )
            except GithubException as e:
                if e.status != 404:
                    raise
                content_unchanged = False
                body_unchanged = False
        else:
            content_unchanged = False
            body_unchanged = False

        # ── Branch lifecycle: delete + recreate only when changes exist ──────
        try:
            _retry(lambda: self._repo.create_git_ref(
                ref=f"refs/heads/{branch}",
                sha=head_sha,
            ))
            if DEBUG:
                print(
                    f"[pr_creator] {technique_id}: created branch '{branch}'")
        except GithubException as e:
            if e.status == 422:
                if DEBUG:
                    print(
                        f"[pr_creator] Branch '{branch}' exists — "
                        f"deleting and recreating from HEAD"
                    )
                ref = self._repo.get_git_ref(f"heads/{branch}")
                _retry(lambda: ref.delete())
                _retry(lambda: self._repo.create_git_ref(
                    ref=f"refs/heads/{branch}",
                    sha=head_sha,
                ))
            else:
                raise

        # ── Commit rule to branch ─────────────────────────────────────────
        skip_commit = False
        if content_unchanged:
            if DEBUG:
                print(f"[pr_creator] Content unchanged — skipping commit")
            skip_commit = True
        else:
            try:
                existing_file = self._repo.get_contents(rule_path, ref=branch)
                _retry(lambda: self._repo.update_file(
                    path=rule_path,
                    message=f"feat: {technique_id} detection rule — automated",
                    content=rule_yaml,
                    sha=existing_file.sha,
                    branch=branch,
                ))
                if DEBUG:
                    print(f"[pr_creator] Updated {rule_path}")
            except GithubException as e:
                if e.status == 404:
                    _retry(lambda: self._repo.create_file(
                        path=rule_path,
                        message=f"feat: {technique_id} detection rule — automated",
                        content=rule_yaml,
                        branch=branch,
                    ))
                    if DEBUG:
                        print(f"[pr_creator] Created {rule_path}")
                else:
                    raise
